"""Initial migration

Revision ID: 70bb23e306f4
Revises: 
Create Date: 2025-01-10 13:57:00.982725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bb23e306f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_group_code', sa.String(), nullable=True),
    sa.Column('custom_field_group_desc', sa.String(), nullable=True),
    sa.Column('loopup_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_group_custom_field_group_code'), 'custom_field_group', ['custom_field_group_code'], unique=False)
    op.create_index(op.f('ix_custom_field_group_id'), 'custom_field_group', ['id'], unique=False)
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('config_group_id', sa.Integer(), nullable=True),
    sa.Column('config_desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['config_group_id'], ['custom_field_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_id'), 'config', ['id'], unique=False)
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_index(op.f('ix_config_id'), table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_custom_field_group_id'), table_name='custom_field_group')
    op.drop_index(op.f('ix_custom_field_group_custom_field_group_code'), table_name='custom_field_group')
    op.drop_table('custom_field_group')
    # ### end Alembic commands ###
